### PR TITLE
make redis and posgres not use public elb

### PR DESCRIPTION
**Pull request by awsmsrc**
we could probably do with removing the 5000 endpoint eventually as that is creating an elb we don't need

### CODE REVIEW

**Comment by awsmsrc** [comment]
also this is currently running on staging

**Comment by tommoor** [comment]
simple!

**Review by tommoor — APPROVED** [review]

**Comment by tommoor** [comment]
This means we need to separate our compose files for dev / prod at this point right? We won't be able to query the local database anymore with this change

**Comment by awsmsrc** [comment]
i was able to access the local database

**Pull request merged**
